package com.thraksha.guardian.data.db

import androidx.room.Entity
import androidx.room.PrimaryKey

/** Encrypted, structured log entry (see SecureLogger). */
@Entity(tableName = "app_log")
data class AppLogEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val timestamp: Long,
    val level: String,
    val tag: String,
    val message: String,
)

/** Key/value configuration (see ConfigStore). */
@Entity(tableName = "config")
data class ConfigEntity(
    @PrimaryKey val key: String,
    val value: String,
)

/**
 * Append-only, hash-chained audit entry (see AuditLog).
 * [id] is client-assigned (not autogenerated) so it can participate in the hash.
 * hash = SHA-256(id | timestamp | type | details | prevHash).
 */
@Entity(tableName = "audit_log")
data class AuditEntity(
    @PrimaryKey val id: Long,
    val timestamp: Long,
    val type: String,
    val details: String,
    val tier: Int,
    val prevHash: String,
    val hash: String,
)
