package com.thraksha.guardian

import com.thraksha.guardian.data.audit.AuditLog
import com.thraksha.guardian.data.db.AuditDao
import com.thraksha.guardian.data.db.AuditEntity
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.async
import kotlinx.coroutines.awaitAll
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flowOf
import kotlinx.coroutines.test.runTest
import kotlinx.coroutines.withContext
import kotlinx.coroutines.yield
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Phase 1: `AuditLog.append` derives the next id from `dao.last()` and then inserts.
 * Once more than one producer exists (the bus collector and the security audit engine)
 * that read-then-write must not interleave, or two appends compute the same id and the
 * non-autogenerated primary key aborts the insert.
 *
 * The fake DAO below yields between the read and the write, which is exactly the
 * interleaving point, and rejects duplicate ids the way Room's ABORT conflict strategy
 * does. Without the Mutex in `append` this test fails.
 */
class AuditLogConcurrencyTest {

    private class FakeAuditDao : AuditDao {
        private val rows = mutableListOf<AuditEntity>()

        override suspend fun insert(entry: AuditEntity) {
            // Widen the race window and mimic Room's ABORT on primary-key conflict.
            yield()
            require(rows.none { it.id == entry.id }) { "duplicate audit id ${entry.id}" }
            rows.add(entry)
        }

        override suspend fun allOrdered(): List<AuditEntity> = rows.sortedBy { it.id }

        override suspend fun last(): AuditEntity? {
            yield()
            return rows.maxByOrNull { it.id }
        }

        override suspend fun count(): Long = rows.size.toLong()

        override fun observeRecent(limit: Int): Flow<List<AuditEntity>> =
            flowOf(rows.sortedByDescending { it.id }.take(limit))

        override suspend fun byId(id: Long): AuditEntity? = rows.firstOrNull { it.id == id }
    }

    @Test
    fun concurrentAppends_produceAUniqueIdPerEntryAndAValidChain() = runTest {
        val dao = FakeAuditDao()
        val log = AuditLog(dao)
        val appends = 50

        withContext(Dispatchers.Default) {
            (1..appends)
                .map { i -> async { log.append(type = "THREAT", details = "finding-$i", tier = i) } }
                .awaitAll()
        }

        val chain = dao.allOrdered()
        assertEquals(appends, chain.size)
        assertEquals(appends, chain.map { it.id }.toSet().size)
        assertEquals((1L..appends).toList(), chain.map { it.id })
        assertTrue("chain must verify after concurrent appends", AuditLog.verify(chain))
    }
}
